### ISSUE TITLE
Can I enumerate all the KeyValuePair of the CompositionPropertySet?

### ISSUE THREAD

**Issue by devkanro** [clarkezone/UWPCompositionDemos#1]
If I want to know which KeyValuePair the CompositionPropertySet have?
What should I do?

Before your demos, I even don't know ScrollViewerManipulationPropertySet have Translation property...

**Comment by clarkezone** [comment]
Hi there.  No, you can't enumerate what's in a CompositionPropertySet right now.  This is the list of constants you can query for:
-   “Translation”
-   “CenterPoint”
-   “Scale”
-   “Matrix”
